### ISSUE TITLE
rstate problem

### ISSUE THREAD

**Issue by carande** [hyperopt/hyperopt-sklearn#35]
Hi, I've been trying to get some examples working using hyperopt-sklearn on the Iris dataset, but haven't had any luck yet.  After modifying the example code so that the iris dataset is loaded and split correctly, I am running into a problem using the demo code: 

```
# Hyperopt SKL estimator
estimator = hpsklearn.HyperoptEstimator(
    preprocessing=hpsklearn.components.any_preprocessing('pp'),
    classifier=hpsklearn.components.any_classifier('clf'),
    algo=hyperopt.tpe.suggest,
    trial_timeout=15.0, # seconds
    max_evals=15,
    )

# Demo version of estimator.fit()
fit_iterator = estimator.fit_iter(X_train,y_train)
fit_iterator.next()
plot_helper = hpsklearn.demo_support.PlotHelper(estimator,
                                                mintodate_ylim=(-.01, .05))
while len(estimator.trials.trials) < estimator.max_evals:
    fit_iterator.send(1) # -- try one more model
    plot_helper.post_iter()
plot_helper.post_loop()

# -- Model selection was done on a subset of the training data.
# -- Now that we've picked a model, train on all training data.
estimator.retrain_best_model_on_full_data(X_train, y_train) 
```

and the error I get back:

```
Traceback (most recent call last):
  File "dir/iris_test.py", line 45, in <module>
    fit_iterator.send(1) # -- try one more model
  File "dir/hyperopt-sklearn/hpsklearn/estimator.py", line 353, in fit_iter
    return_argmin=False, # -- in case no success so far
TypeError: fmin() got an unexpected keyword argument 'rstate'
```

**Comment by crazy449** [comment]
I tried this and I get an issue with distribute. I get:

```
Obtaining file:///home/vagrant/hyperopt
  Running setup.py (path:/home/vagrant/hyperopt/setup.py) egg_info for package from file:///home/vagrant/hyperopt
    Extracting in /tmp/tmpSMITP1
    Now working in /tmp/tmpSMITP1/distribute-0.6.38
    Building a Distribute egg in /home/vagrant/hyperopt
    Traceback (most recent call last):
      File "setup.py", line 248, in <module>
        scripts = scripts,
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/tmpSMITP1/distribute-0.6.38/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/tmp/tmpSMITP1/distribute-0.6.38/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2027, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2237, in requires
        dm = self._dep_map
      File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2466, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2499, in _compute_dependencies
        common = frozenset(reqs_for_extra(None))
      File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2496, in reqs_for_extra
        if req.marker_fn(override={'extra':extra}):
      File "/tmp/tmpSMITP1/distribute-0.6.38/_markerlib/markers.py", line 109, in marker_fn
        return eval(compiled_marker, environment)
      File "<environment marker>", line 1, in <module>
    NameError: name 'sys_platform' is not defined
    /home/vagrant/hyperopt/distribute-0.6.38-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/vagrant/hyperopt/setup.py", line 37, in <module>
        distribute_setup.use_setuptools()
      File "distribute_setup.py", line 152, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "distribute_setup.py", line 132, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "distribute_setup.py", line 123, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    Complete output from command python setup.py egg_info:
    Extracting in /tmp/tmpSMITP1

Now working in /tmp/tmpSMITP1/distribute-0.6.38

Building a Distribute egg in /home/vagrant/hyperopt

Traceback (most recent call last):

  File "setup.py", line 248, in <module>

    scripts = scripts,

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/tmp/tmpSMITP1/distribute-0.6.38/setuptools/dist.py", line 225, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/tmp/tmpSMITP1/distribute-0.6.38/setuptools/dist.py", line 257, in finalize_options

    ep.require(installer=self.fetch_build_egg)

  File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2027, in require

    working_set.resolve(self.dist.requires(self.extras),env,installer))

  File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2237, in requires

    dm = self._dep_map

  File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2466, in _dep_map

    self.__dep_map = self._compute_dependencies()

  File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2499, in _compute_dependencies

    common = frozenset(reqs_for_extra(None))

  File "/tmp/tmpSMITP1/distribute-0.6.38/pkg_resources.py", line 2496, in reqs_for_extra

    if req.marker_fn(override={'extra':extra}):

  File "/tmp/tmpSMITP1/distribute-0.6.38/_markerlib/markers.py", line 109, in marker_fn

    return eval(compiled_marker, environment)

  File "<environment marker>", line 1, in <module>

NameError: name 'sys_platform' is not defined

/home/vagrant/hyperopt/distribute-0.6.38-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/vagrant/hyperopt/setup.py", line 37, in <module>

    distribute_setup.use_setuptools()

  File "distribute_setup.py", line 152, in use_setuptools

    return _do_download(version, download_base, to_dir, download_delay)

  File "distribute_setup.py", line 132, in _do_download

    _build_egg(egg, tarball, to_dir)

  File "distribute_setup.py", line 123, in _build_egg

    raise IOError('Could not build the egg.')

IOError: Could not build the egg.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/vagrant/hyperopt
Storing debug log for failure in /home/vagrant/.pip/pip.log`
```


Any ideas?

**Comment by lesson1221** [comment]
I met the same rstate problem. It seems that the function fmin() in lastest version of hyperopt has some conflict with fmin() in hyperopt-sklearn. Is there any way to solve this problem? Thanks if someone can help me

**Comment by nipunsadvilkar** [comment]
Facing similar issue

`TypeError: fmin() got an unexpected keyword argument 'rstate'`

Any solution for this?

**Comment by bjkomer** [comment]
I've started working on a fix for this. hyperopt-sklearn is only compatible with newer versions of hyperopt from github, and not the older on that is on PyPI. I'm hoping to get in a workaround to make it backwards compatible, but it looks like there are more issues than just the arguments not matching up.

The easiest thing to do in the meantime would be to install hyperopt from github and use that version.

**Comment by bjkomer** [comment]
@crazy449 I'm seeing a similar error when I try to install using `distrubute_setup.py` on `hyperopt`

I'm not familiar with distribute, so I don't know what's going on there. Do other methods of installation work for you?

I commonly do (from within the `hyperopt` folder): `pip install -e .` and I think `python setup.py install` may work as well

**Comment by zpardos** [comment]
running the Hyperas example (https://github.com/maxpumperla/hyperas), I get a very similar error. I don't think Hyperas uses hyperopt-sklearn, so it looks to be an issue with hyperopt.

`Traceback (most recent call last):
  File "hyper_example.py", line 77, in <module>
    trials=Trials())
  File "/usr/local/lib/python3.5/dist-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "/usr/local/lib/python3.5/dist-packages/hyperas/optim.py", line 111, in base_minimizer
    rseed=rseed)
TypeError: fmin() got an unexpected keyword argument 'rseed'
`

**Comment by tkrishp** [comment]
I'm having same problem when running the example provided in Hyperas (as pointed out @zpardos ). Does anyone know how to fix it?

```
Traceback (most recent call last):
  File "grid_search.py", line 77, in <module>
    trials=Trials())
  File "/opt/anaconda2/envs/thesis/lib/python2.7/site-packages/hyperas/optim.py", line 31, in minimize
    best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
  File "/opt/anaconda2/envs/thesis/lib/python2.7/site-packages/hyperas/optim.py", line 111, in base_minimizer
    rseed=rseed)
TypeError: fmin() got an unexpected keyword argument 'rseed'
```

**Comment by jaganadhg** [comment]
The ISSUE is still there 

```
C:\Users\jaganadhg\AppData\Local\Continuum\Anaconda2\lib\site-packages\hpsklearn\estimator.pyc in fit_iter(self, X, y, EX_list, valid_size, n_folds, cv_shuffle, random_state, weights, increment)
    582                           #    so we notice them.
    583                           catch_eval_exceptions=False,
--> 584                           return_argmin=False,  # -- in case no success so far
    585                          )
    586 

TypeError: fmin() got an unexpected keyword argument 'rstate'
```

**Comment by bjkomer** [comment]
This should hopefully be working now. `hyperopt-sklearn` will now check to see if you are using an older version of `hyperopt` and use the correct parameter names for it.

**Comment by ChristoferNal** [comment]
@tkrishp @zpardos I have the same issue with hyperopt-0.0.3.dev0
Have you found any solution?

**Comment by hyperdo** [comment]
@tkrishp @zpardos bump. Any movement on this?

**Comment by Benjamin-Lee** [comment]
Still having the issue on with version 0.2.

**Comment by iyliamjd** [comment]
> Still having the issue on with version 0.2.
> 
> ```
> Traceback (most recent call last):
>   File "basic_hyperas_test.py", line 27, in <module>
>     trials=Trials())
>   File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 31, in minimize
>     best_run = base_minimizer(model, data, algo, max_evals, trials, rseed)
>   File "/usr/local/lib/python2.7/dist-packages/hyperas/optim.py", line 111, in base_minimizer
>     rseed=rseed)
> TypeError: fmin() got an unexpected keyword argument 'rseed'
> ```

I also got this issue, have anyone solve it? Because when I change to randomState(seed). got a lot untrace errors

**Comment by bjkomer** [comment]
@Benjamin-Lee @iyliamjd from the trace of your error the issue is from the package `hyperas` and not `hyperopt-sklearn`. The core of the issue is an older version of `hyperopt` had a parameter called `rseed` but that has been replaced with `rstate` (this change was made about 6 years ago).

`hyperopt-sklearn` has been made to be backwards compatible with both version, and it [looks like](https://github.com/maxpumperla/hyperas/blame/43cd3a4dfe907e17fd87807b985ddc5a811b25f6/hyperas/optim.py#L121) `hyperas` has as well. Likely you just need to update to the latest versions of these packages from github.
